In [1]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
music_data = pd.read_csv('data.csv')
music_data

filename       tempo  beats  chroma_stft      rmse  \
0    blues.00081.au  103.359375     50     0.380260  0.248262   
1    blues.00022.au   95.703125     44     0.306451  0.113475   
2    blues.00031.au  151.999081     75     0.253487  0.151571   
3    blues.00012.au  184.570312     91     0.269320  0.119072   
4    blues.00056.au  161.499023     74     0.391059  0.137728   
..              ...         ...    ...          ...       ...   
995   rock.00017.au  123.046875     59     0.418812  0.166056   
996   rock.00081.au  117.453835     56     0.335774  0.093676   
997   rock.00004.au  103.359375     45     0.372834  0.208743   
998   rock.00006.au  112.347147     45     0.344472  0.180163   
999   rock.00066.au   75.999540     36     0.360098  0.042995   

     spectral_centroid  spectral_bandwidth      rolloff  zero_crossing_rate  \
0          2116.942959         1956.611056  4196.107960            0.127272   
1          1156.070496         1497.668176  2170.053545            0.058613   
2          1331.073970         1973.643437  2900.174130            0.042967   
3          1361.045467         1567.804596  2739.625101            0.069124   
4          1811.076084         2052.332563  3927.809582            0.075480   
..                 ...                 ...          ...                 ...   
995        2312.030070         2060.825761  4528.197619            0.140588   
996        2553.856706         2219.090892  5123.752351            0.136173   
997        1345.850763         1841.748033  2939.265560            0.041099   
998        1675.475369         1653.422860  3253.563659            0.087294   
999        2209.357588         2175.214294  4575.588999            0.107147   

          mfcc1  ...     mfcc12     mfcc13    mfcc14    mfcc15    mfcc16  \
0    -26.929785  ...  14.336612 -13.821769  7.562789 -6.181372  0.330165   
1   -233.860772  ...  -2.250578   3.959198  5.322555  0.812028 -1.107202   
2   -221.802549  ... -13.037723 -12.652228 -1.821905 -7.260097 -6.660252   
3   -207.208080  ...  -0.613248   0.384877  2.605128 -5.188924 -9.527455   
4   -145.434568  ...   7.457218 -10.470444 -2.360483 -6.783623  2.671134   
..          ...  ...        ...        ...       ...       ...       ...   
995  -41.402023  ...  11.303100 -14.155566  2.824157 -9.477822  3.331261   
996 -121.410791  ...   9.149520 -10.112054  4.211237 -9.349345  1.609701   
997 -127.946876  ...  11.043714  -8.385375  2.111019 -6.338260  0.997383   
998  -98.356322  ...   2.945863 -12.509212  0.091337 -0.774780 -5.700102   
999 -245.160921  ...   0.813777 -13.018359  0.053168 -8.232851  1.059255   

        mfcc17     mfcc18     mfcc19     mfcc20  label  
0    -6.829571   0.965922  -7.570825   2.918987  blues  
1    -4.556555  -2.436490   3.316913  -0.608485  blues  
2   -14.682694 -11.719264 -11.025216 -13.387260  blues  
3    -9.244394  -2.848274  -1.418707  -5.932607  blues  
4    -4.760879  -0.949005   0.024832  -2.005315  blues  
..         ...        ...        ...        ...    ...  
995  -8.200088   3.693091  -3.673562  -0.163201   rock  
996 -10.553566   1.066489  -1.654875   7.544224   rock  
997  -5.325869  -0.842192  -4.665996  -4.787677   rock  
998  -8.630916  -1.903803  -2.196753  -3.395148   rock  
999  -8.031864  -0.397097  -4.349921  -4.220998   rock  

[1000 rows x 30 columns]

In [218]:
music = music_data[['tempo','beats','label']]
music

tempo  beats  label
0    103.359375     50  blues
1     95.703125     44  blues
2    151.999081     75  blues
3    184.570312     91  blues
4    161.499023     74  blues
..          ...    ...    ...
995  123.046875     59   rock
996  117.453835     56   rock
997  103.359375     45   rock
998  112.347147     45   rock
999   75.999540     36   rock

[1000 rows x 3 columns]

In [238]:
from sklearn.utils import resample
df_label = resample(music,n_samples=20)
# sampling
df_label
#keep the label data to check the clustering result with original dataset

tempo  beats      label
836  151.999081     73     reggae
531  151.999081     71       jazz
206  112.347147     55    country
804  172.265625     86     reggae
391  107.666016     52      disco
649  117.453835     57      metal
999   75.999540     36       rock
14   135.999178     67      blues
80   107.666016     51      blues
763  112.347147     54        pop
753  129.199219     61        pop
726  107.666016     53        pop
890   99.384014     49     reggae
857  135.999178     66     reggae
491  129.199219     63     hiphop
238  151.999081     74    country
124  117.453835     46  classical
504  107.666016     51       jazz
631  129.199219     61      metal
572  123.046875     59       jazz

In [240]:
df = df_label[['tempo','beats']]
kmeans = KMeans(n_clusters=10, random_state=0,init='k-means++', n_init="auto").fit(df.values)
#sklearn only fitted with values
kmeans.labels_
#memory leak warning -> environment variable setting

C:\Users\jenny\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


array([2, 2, 1, 4, 8, 1, 3, 7, 8, 1, 0, 8, 6, 7, 0, 2, 5, 8, 0, 9])

In [242]:
import random

tmp_max = df['tempo'].max()
tmp_min = df['tempo'].min()

beat_max = df['beats'].max()
beat_min = df['beats'].min()

x1 = random.uniform(tmp_min,tmp_max)
x2 = random.uniform(tmp_min,tmp_max)
y1 = random.randint(beat_min,beat_max)
y2 = random.randint(beat_min,beat_max)

arr = [x1,y1,x2,y2]
print('arr:',arr)

arr: [147.92541762409283, 48, 90.82166012689268, 53]


In [244]:
kmeans.predict([[x1,y1],[x2,y2]])

array([7, 6])

In [292]:
from sklearn.cluster import AgglomerativeClustering
clustering = AgglomerativeClustering(n_clusters=10,linkage='complete',metric='l2').fit(df.values)
clustering

AgglomerativeClustering(linkage='complete', metric='l2', n_clusters=10)

In [290]:
clustering.labels_

array([1, 1, 4, 9, 2, 0, 5, 8, 2, 4, 3, 2, 6, 8, 3, 1, 7, 2, 3, 0],
      dtype=int64)

In [322]:
from sklearn.cluster import DBSCAN
dbscan = DBSCAN(eps=3,min_samples=1).fit(df.values)
dbscan

DBSCAN(eps=3, min_samples=1)

In [324]:
dbscan.labels_

array([ 0,  0,  1,  2,  3,  4,  5,  6,  3,  1,  7,  3,  8,  6,  7,  0,  9,
        3,  7, 10], dtype=int64)

In [334]:
labels = df_label[['label']]
labels

label
836     reggae
531       jazz
206    country
804     reggae
391      disco
649      metal
999       rock
14       blues
80       blues
763        pop
753        pop
726        pop
890     reggae
857     reggae
491     hiphop
238    country
124  classical
504       jazz
631      metal
572       jazz

In [414]:
a = labels[0:4]
b = labels[4:8]
a

label
836   reggae
531     jazz
206  country
804   reggae

In [398]:
from sklearn.metrics.cluster import normalized_mutual_info_score
normalized_mutual_info_score(a.values.flatten(),b.values.flatten())

0.8571428571428571

In [428]:
df_beat = df[['beats']]
df_beat

beats
836     73
531     71
206     55
804     86
391     52
649     57
999     36
14      67
80      51
763     54
753     61
726     53
890     49
857     66
491     63
238     74
124     46
504     51
631     61
572     59

In [432]:
a = df_beat[0:4]
b = df_beat[4:8]
normalized_mutual_info_score(a.values.flatten(),b.values.flatten())

1.0

In [436]:
from sklearn.metrics import silhouette_score
kmeans = KMeans(n_clusters=2,random_state=1)#固定不要進行random
silhouette_score(df,kmeans.fit_predict(df))

C:\Users\jenny\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


0.5434159620225748